version: "3.9"

services:
  api:
    image: fawazsullia/micro-apis:0.0.3
    container_name: api
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped

  worker:
    image: fawazsullia/micro-apis:0.0.3
    container_name: youtube_worker
    command: ["python3", "-m", "workers.process_youtube_links"]
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - api

  dashboard:
    image: fawazsullia/yt-tools-ui:0.0.3
    container_name: dashboard
    ports:
      - "8080:8080"  # Assumes Nginx is serving it
    env_file:
      - .env
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - dashboard
